name: Build & Deploy Cloud Run

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: uas-udb-ti2401
  GAR_LOCATION: us-west1
  REPOSITORY: uas-repo
  IMAGE_NAME: uas-udb-ti2401
  PROJECT_ID: project-d84633c5-a53e-4ac3-9a4

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.export-image.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

      - name: Build image
        run: |
          docker build -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .

      - name: Push image
        run: |
          docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}

      - name: Export image name
        id: export-image
        run: |
          echo "image=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Debug image
        run: echo "IMAGE=${{ needs.build.outputs.image }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image "${{ needs.build.outputs.image }}" \
            --region $GAR_LOCATION \
            --platform managed \
            --allow-unauthenticated
